2025-08-26 13:59:57 | INFO | access | GET /docs -> 200
2025-08-26 13:59:58 | INFO | access | GET /openapi.json -> 200
2025-08-26 14:01:08 | ERROR | access | GET /v1/manual/call-finished crashed: 1 validation error for ManualCallPayload
client_id
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
Traceback (most recent call last):
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\anyio\streams\memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\dialdesk-callmaster\React_Fastapi\main.py", line 102, in access_log_mw
    resp = await call_next(request)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\base.py", line 154, in call_next
    raise app_exc
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Project\dialdesk-callmaster\React_Fastapi\routers\manual_call.py", line 126, in manual_call_finished
    payload = ManualCallPayload(**incoming)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ManualCallPayload
client_id
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
2025-08-26 14:02:22 | ERROR | access | GET /v1/manual/call-finished crashed: 3 validation errors for ManualCallPayload
lead_id
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='--A--lead_id--B--', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/int_parsing
call_duration_sec
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='--A--talk_time--B--', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/int_parsing
recording_location
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='--A--recording_location--B--', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/url_parsing
Traceback (most recent call last):
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\anyio\streams\memory.py", line 124, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\dialdesk-callmaster\React_Fastapi\main.py", line 102, in access_log_mw
    resp = await call_next(request)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\base.py", line 154, in call_next
    raise app_exc
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Project\dialdesk-callmaster\React_Fastapi\routers\manual_call.py", line 126, in manual_call_finished
    payload = ManualCallPayload(**incoming)
  File "D:\Project\dialdesk-callmaster\.venv\lib\site-packages\pydantic\main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for ManualCallPayload
lead_id
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='--A--lead_id--B--', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/int_parsing
call_duration_sec
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='--A--talk_time--B--', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/int_parsing
recording_location
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='--A--recording_location--B--', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/url_parsing
2025-08-26 14:02:22 | INFO | access | GET /favicon.ico -> 404
2025-08-26 14:07:12 | INFO | access | GET /v1/manual/call-finished   -> 404
2025-08-26 14:10:31 | INFO | access | GET /v1/manual/call-finished   -> 404
2025-08-26 14:12:33 | INFO | access | GET /v1/manual/call-finished -> 404
2025-08-26 14:12:49 | INFO | access | GET /v1/manual/call-finished -> 404
2025-08-26 14:47:09 | INFO | access | GET /v1/manual/call-finished -> 404
2025-08-26 14:52:41 | INFO | access | GET /v1/manual/call-finished -> 404
2025-08-26 14:52:54 | INFO | access | GET /docs -> 200
2025-08-26 14:52:54 | INFO | access | GET /openapi.json -> 200
2025-08-26 14:53:37 | INFO | access | GET /docs -> 200
2025-08-26 14:53:37 | INFO | access | GET /openapi.json -> 200
2025-08-26 14:55:05 | INFO | access | GET /v1/manual/call-finished -> 404
2025-08-26 14:55:25 | INFO | access | GET /v1/v1/manual/call-finished -> 404
2025-08-26 14:55:35 | INFO | access | GET /v1/manual/call-finished -> 404
2025-08-26 14:55:47 | INFO | access | GET /docs -> 200
2025-08-26 14:55:48 | INFO | access | GET /openapi.json -> 200
2025-08-26 15:01:55 | INFO | access | GET /docs -> 200
2025-08-26 15:01:55 | INFO | access | GET /openapi.json -> 200
2025-08-26 15:05:06 | INFO | access | GET /docs -> 200
2025-08-26 15:05:06 | INFO | access | GET /openapi.json -> 200
2025-08-26 15:08:12 | INFO | access | GET /docs -> 200
2025-08-26 15:08:12 | INFO | access | GET /openapi.json -> 200
2025-08-26 15:08:48 | INFO | access | GET /health -> 200
2025-08-26 15:09:07 | INFO | access | GET /v1/manual/call-finished -> 404
2025-08-26 15:09:32 | INFO | access | GET /docs -> 200
2025-08-26 15:09:32 | INFO | access | GET /openapi.json -> 200
2025-08-26 15:09:37 | INFO | access | GET /docs -> 200
2025-08-26 15:09:38 | INFO | access | GET /openapi.json -> 200
2025-08-26 15:16:47 | INFO | access | GET /v1/manual/call-finished -> 405
2025-08-26 15:21:02 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:23:16 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:27:47 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:29:25 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:32:48 | INFO | access | GET /docs -> 200
2025-08-26 15:32:48 | INFO | access | GET /docs -> 200
2025-08-26 15:32:48 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:32:48 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:33:47 | INFO | access | GET /docs -> 200
2025-08-26 15:33:47 | INFO | access | GET /openapi.json -> 200
2025-08-26 15:33:59 | INFO | access | POST /dashboard3/summary -> 200
2025-08-26 15:35:13 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:37:18 | INFO | access | GET /docs -> 200
2025-08-26 15:37:18 | INFO | access | GET /openapi.json -> 200
2025-08-26 15:37:37 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:41:34 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:44:32 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 15:46:10 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 17:10:40 | INFO | access | GET /v1/manual/call-finished -> 200
2025-08-26 18:21:25 | INFO | access | GET /docs -> 200
2025-08-26 18:21:28 | INFO | access | GET /openapi.json -> 200
2025-08-26 18:21:32 | INFO | access | GET /v1/manual/call-finished -> 200
